### Get all customer orders
GET http://localhost:3000/customerOrders/

### Get a customer order by order ID
GET http://localhost:3000/customerOrders/id/1

### Get all customer orders for a specific customer
GET http://localhost:3000/customerOrders/user/1

### Create a new shopping card item
POST  http://localhost:3000/customerOrders/
content-type: application/json

{
  "person": 10,
  "orderTime": "2021-06-15",
  "shippingTime": "2021-06-27",
  "trackingNumber": "ABKU005Z"
}

### Update customer order by its ID
PUT  http://localhost:3000/customerOrders/10
content-type: application/json

{
  "person": 10,
  "orderTime": "2016-06-22 19:10:25-02",
  "shippingTime": "2021-06-22 22:10:25-02",
  "trackingNumber": "ABKU005Z"
}

### Update customer order by its ID
PUT  http://localhost:3000/customerOrders/shippingInformation/2
content-type: application/json

{
  "shippingTime": "2023-06-22 22:10:25-02",
  "trackingNumber": "ABKU005Z"
}

### Update customer order shipping time

PATCH http://localhost:3000/customerOrders/setShippingTime/2
content-type: application/json

{
  "shippingTime": "2020-06-22 22:10:25-02"
}

### Update customer order shipping tracking number

PATCH http://localhost:3000/customerOrders/trackingNumber/2
content-type: application/json

{
  "trackingNumber": "ABKU005Z0001"
}


### DELETE a customer order by its id
DELETE  http://localhost:3000/customerOrders/2