### Get all existing shopping card items
GET http://localhost:3000/shoppingCards/all

### Get all shopping card items for a user
GET http://localhost:3000/shoppingCards/user/1

### Create a new shopping card item
POST  http://localhost:3000/shoppingCards/single
content-type: application/json

{
  "product": 23,
  "amount": 0,
  "size": "s",
  "color": "black",
  "person": 1
}

### Create many new shopping card item
POST  http://localhost:3000/shoppingCards/many
content-type: application/json

[
  {
    "product": 23,
    "amount": 5,
    "size": "M",
    "color": "black",
    "person": 1
  },
  {
    "product": 23,
    "amount": 4,
    "size": "l",
    "color": "Navy",
    "person": 1
  },
  {
    "product": 26,
    "amount": 4,
    "size": "S",
    "color": "green",
    "person": 1
  },
  {
    "product": 26,
    "amount": 0,
    "size": "m",
    "color": "green",
    "person": 1
  }
]


### Update a shopping card item
PUT  http://localhost:3000/shoppingCards/5
content-type: application/json

{
  "amount": -10,
  "size": "L",
  "color": "blue"
}

### DELETE a shopping card item by its id
DELETE  http://localhost:3000/shoppingCards/deleteSingle/21

### DELETE all shopping card items of a user by the user ID
DELETE  http://localhost:3000/shoppingCards/deleteByUser/1