### GET all tags
GET http://localhost:3000/products

### Update a single product by id
GET  http://localhost:3000/products/category/3

### Update a single product by id
GET  http://localhost:3000/products/4

### Create a new product
POST  http://localhost:3000/products
content-type: application/json

{
  "title": "WBS Computer New Version XXX",
  "description": "New Computer with category",
  "categories": [2, 4]
}

### Update a product
PUT  http://localhost:3000/products/11
content-type: application/json

{
  "title": "New WBS",
  "description": "A nice t-shirt with the WBS logo",
  "categories": [2]
}

### Delete a product
DELETE  http://localhost:3000/products/3